title = "Nitisha Singh"

# 1. Replace hsrai with your userID on code.gndec.ac.in server
#baseURL = "http://code.gndec.ac.in/~2017098/www"
# 2. Type # at the beginning of above line

# 2. Remove # from line below and replace hsrai with your userID at github 
baseURL = "https://nitisha2017098.github.io/www"

# 2. Remove # from line below
publishDir = "docs"

# 2. Type # at the beginning of line below
#publishDir = "../public_html/www"

languageCode = "en-us"
theme = "ananke"
themesDir = "themes"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = "work from GNDEC,elecronics engineering"
  description = "Master trainer: Empowering Folk"
  facebook = "https://facebook.com/GoHugoIO"
  twitter = "https://twitter.com/GoHugoIO"
  instagram = "https://instagram.com/GoHugoIO"
  youtube = "https://youtube.com/GoHugoIO"
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "grey-green"
  featured_image = "https://visualhunt.com/photos/1/young-woman-reading-book.jpg?s=s"
  recent_posts_number = 2
